coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 1%

comment:
  layout: "header, diff, flags, components"

component_management:
  individual_components:
    - component_id: api
      name: api
      paths:
        - api
